CREATE TABLE  Users
(
Id INT NOT NULL PRIMARY KEY IDENTITY,
Username VARCHAR(30) NOT NULL UNIQUE,
Password VARCHAR(50) NOT NULL,
Name VARCHAR(50) ,
Birthdate DATETIME ,
Age INT CHECK(Age>=14 AND Age<=110),
Email VARCHAR (50) NOT NULL
)
CREATE TABLE Departments
(
Id INT NOT NULL PRIMARY KEY IDENTITY,
Name VARCHAR (50) NOT NULL
)
CREATE TABLE Employees
(
Id INT NOT NULL PRIMARY KEY IDENTITY,
FirstName VARCHAR(25),
LastName VARCHAR(25),
Birthdate DATETIME ,
Age INT CHECK(Age>=14 AND Age<=110),
DepartmentId INT REFERENCES Departments(Id)
)
CREATE TABLE Categories
(
Id INT NOT NULL PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL,
DepartmentId INT REFERENCES Departments(Id) NOT NULL
)
CREATE TABLE Status
(
Id INT NOT NULL PRIMARY KEY IDENTITY,
Label VARCHAR(30) NOT NULL,
)
CREATE TABLE Reports 
(
Id INT NOT NULL PRIMARY KEY IDENTITY,
CategoryId INT NOT NULL REFERENCES Categories(Id),
StatusId INT NOT NULL REFERENCES Status(Id),
OpenDate DATETIME NOT NULL,
CloseDate DATETIME ,
Description VARCHAR(200) NOT NULL,
UserId INT REFERENCES Users(Id) NOT NULL,
EmployeeId INT REFERENCES Employees(Id)
)