CREATE TABLE Users
(
Id INT PRIMARY KEY NOT NULL IDENTITY,
Username VARCHAR(30) NOT NULL,
Password VARCHAR(30) NOT NULL,
Email VARCHAR(50) NOT NULL,
)
CREATE TABLE Repositories
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name VARCHAR(50) NOT NULL,
)
CREATE TABLE RepositoriesContributors
(
RepositoryId INT NOT NULL REFERENCES Repositories(Id),
ContributorId INT NOT NULL REFERENCES Users(Id),
PRIMARY KEY(RepositoryId,ContributorId)
)
CREATE TABLE Issues 
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Title VARCHAR(255) NOT NULL,
IssueStatus CHAR(6) NOT NULL,
RepositoryId INT NOT NULL REFERENCES Repositories(Id),
AssigneeId INT NOT NULL REFERENCES Users(Id)
)
CREATE TABLE Commits
(
Id INT IDENTITY PRIMARY KEY NOT NULL ,
Message VARCHAR(255) NOT NULL,
IssueId INT REFERENCES Issues(Id),
RepositoryId INT NOT NULL REFERENCES Repositories(Id), 
ContributorId INT NOT NULL REFERENCES Users(Id)
)
CREATE TABLE Files
(
Id INT IDENTITY NOT NULL PRIMARY KEY ,
Name VARCHAR(100) NOT NULL,
Size DECIMAL (18,2) NOT NULL,
ParentId  INT REFERENCES Files(Id),
CommitId INT NOT NULL REFERENCES Commits(Id)
)